[package]
name = "json_parsing_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# alloy = { version = "0.1.3", features = ["full"] }
